CREATE TABLE user(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL

);

CREATE TABLE score(
	id INTEGER PRIMARY KEY NOT NULL,
	score INTGER NOT NULL
);

